repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgresql
    chart: bitnami/postgresql
    version: 11.1.3
    namespace: databases
    values:
      - postgresql.yaml
    secrets:
      - postgresql-secrets.yaml
